apps/cart/urls.py
from django.conf.urls import  url
from apps.cart.views import AddCartView,CartInfoView,UpdateCartView,DeleteCartView
from apps.cart import views
urlpatterns = [
    url(r'^add$',AddCartView.as_view(),name='addcart'),

    url(r'^$',CartInfoView.as_view(),name='cart'),

    url(r'^update$',UpdateCartView.as_view(),name='updatecart'),

    url(r'^delete$',DeleteCartView.as_view(),name='deletecart'),

]

apps/goods/urls.py
from django.conf.urls import  url

from apps.goods.views import IndexView,DetailView,ListView
urlpatterns = [

    url(r'^index$',IndexView.as_view(),name='index'),

    url(r'^goods/(\d+)$',DetailView.as_view(),name='detail'),

    url(r'^list/(\d+)/(\d+)',ListView.as_view(),name='list'),


]

apps/order/urls.py
from django.conf.urls import  url
from apps.order.views import OrderPlaceView,OrderCommitView,OrderPayView,CommentView

urlpatterns = [

    url(r'^place$',OrderPlaceView.as_view(),name='place'),

    url(r'^commit$',OrderCommitView.as_view(),name='commit'),

    url(r'^pay$',OrderPayView.as_view(),name='pay'),

    url(r'comment/(\d+)$',CommentView.as_view(),name='comment')


]

apps/user/urls.py
from django.conf.urls import  url

# from user import views
from django.contrib.auth.decorators import login_required
from apps.user.views import RegisterView,ActiveView,LoginView,UserAddrView,UserOrderView,UserInfoView,LogoutView
urlpatterns = [
    url(r'^register$',RegisterView.as_view(),name='register'),

    # url(r'^register_handle$',views.register_handle,name='register_handle'),

    # url(r'^active/(?P<id>\.*)$')
    url(r'^active/(.*)$',ActiveView.as_view()),

    url(r'^login$',LoginView.as_view(),name='login'),

    url(r'^logout$',LogoutView.as_view(),name='logout'),

    # url(r'^$',login_required(UserInfoView.as_view()),name ='user'),
    #
    # url(r'^order$',login_required(UserOrderView.as_view()),name='order'),
    #
    # url(r'^address$',login_required(UserAddrView.as_view()),name='address'),
    url(r'^$',UserInfoView.as_view(),name ='user'),

    url(r'^order/(\d+)$',UserOrderView.as_view(),name='order'),

    url(r'^address$',UserAddrView.as_view(),name='address'),
]

dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^user/',include('user.urls',namespace='user')),
    url(r'^order/',include('order.urls',namespace='order')),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'search',include('haystack.urls')),
    url(r'^',include('goods.urls',namespace='goods')),
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from apps.goods.models import GoodsSKU
from django_redis import get_redis_connection
from django.conf import settings
from utils.mixin import LoginRequiredMixin
# Create your views here.
class AddCartView(View):
    def post(self,request):
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res':0,'errmsg':'请先登录'})
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        if not all([sku_id,count]):
            return JsonResponse({'res':1,'errmsg':'数据不完整'})
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res':2,'errmsg':'商品数目不正确'})
        try:
            goodsku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res':3,'errmsg':'没有这个商品'})
        conn = get_redis_connection('default')
        cart_id = 'cart_%s'%user.id
        cart_count = conn.hget(cart_id,sku_id)
        if cart_count:
            count += int(cart_count)
        if count>goodsku.stock:
            return JsonResponse({'res':4,'errmsg':'库存不够'})
        conn.hset(cart_id,sku_id,count)
        num = conn.hlen(cart_id)
        return JsonResponse({'res':5,'num':num,'message':'添加成功'})


class CartInfoView(LoginRequiredMixin,View):
    def get(self,request):
        user = request.user
        cart_id = 'cart_%s'%user.id
        conn = get_redis_connection('default')
        cart_dict = conn.hgetall(cart_id)
        totalcount = 0
        totalprice = 0
        skus = []
        for sku_id,count in cart_dict.items():
            sku = GoodsSKU.objects.get(id=sku_id)
            skus.append(sku)
            amount = sku.price*int(count)
            sku.amount = amount
            sku.count = count
            totalcount += int(count)
            totalprice += amount
        url = settings.NGINX_URL
        content = {

            'skus':skus,
            'totalcount':totalcount,
            'totalprice':totalprice,
            'url':url
        }

        return render(request,'cart.html',content)

class UpdateCartView(View):
    def post(self,request):
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res':0,'errmsg':'请先登录'})
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        print(sku_id,count)
        if not all([sku_id,count]):
            return JsonResponse({'res':1,'errmsg':'信息不完整'})
        try:
            sku = GoodsSKU.objects.get(id = sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res':2,'errmsg':'没有这个商品'})
        try:
            count = int(count)
        except Exception:
            return JsonResponse({'res':3,'errmsg':'商品数量有误'})
        if count > sku.stock:
            return JsonResponse({'res':4,'errmsg':'商品库存不足'})
        conn = get_redis_connection('default')
        cart_id = 'cart_%s'%user.id
        conn.hset(cart_id,sku_id,count)
        count_list = conn.hvals(cart_id)
        total_count = 0
        for num in count_list:
            total_count += int(num)
        return JsonResponse({'res':5,'message':'数据更新成功','total_count':total_count})

class DeleteCartView(View):
    def post(self,request):
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res':0,'errmsg':'请先登录'})
        sku_id = request.POST.get('sku_id')
        if not sku_id:
            return JsonResponse({'res':1,'errmsg':'商品不存在'})
        try:
           sku = GoodsSKU.objects.get(id= sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res':2,'errmsg':'商品不存在'})
        conn = get_redis_connection('default')
        cart_id = 'cart_%s'%user.id
        conn.hdel(cart_id,sku_id)
        count_list = conn.hvals(cart_id)
        total_count = 0
        for val in count_list:
            total_count += int(val)
        return JsonResponse({'res':3,'message':'更新成功','total_count':total_count})

templates/base.html
{#首页，登陆，注册#}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static from staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main(1).css' %}">
	{% block topfile %}{% endblock topfile %}
</head>
<body>
   {% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
    {% endblock header_con %}
   {% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="http://127.0.0.1:8888/static/images/logo.png"></a>
		<div class="search_con fl">
            <form method="get" action="/search">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
    {% endblock search_bar %}
	{% block body %}
    {% endblock body  %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% block bottom %}{% endblock bottom %}
	{% block bottomfiles %}
    {% endblock bottomfiles %}
</body>
</html>

templates/base_detail_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}?sort=default" class="{{ type.logo }}">{{ type.name }}</a></li>

                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">天天生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/base_static.html
{#首页，登陆，注册#}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static from staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main(1).css' %}">
	{% block topfile %}{% endblock topfile %}
</head>
<body>
   {% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">

				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>

				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
    {% endblock header_con %}
   {% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
    {% endblock search_bar %}
	{% block body %}
    {% endblock body  %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% block bottom %}{% endblock bottom %}
	{% block bottomfiles %}
    {% endblock bottomfiles %}
</body>
</html>

templates/cart.html
{% extends 'base_no_cart.html' %}
{% block title %}天天生鲜-购物车{% endblock title %}
{% block page_title %}购物车{% endblock page_title %}
{% block body %}




	<div class="total_count">全部商品<em>{{ totalcount }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form  method="post" action="{% url 'order:place' %}">
    {% for sku in skus %}
	<ul class="cart_list_td clearfix">

		<li class="col01"><input type="checkbox" name="sku_ids" value="{{ sku.id }}" checked=""></li>
		<li class="col02"><img src="{{ url }}/media/{{ sku.image }}"></li>
		<li class="col03">{{ sku.name }}<br><em>{{ sku.price }}元/{{ sku.unite }}</em></li>
		<li class="col04">{{ sku.unite }}</li>
		<li class="col05">{{ sku.price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" sku_id="{{ sku.id }}" class="num_show fl" value="{{ sku.count }}">
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">{{ sku.amount }}元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>

	</ul>
      {% endfor %}

	

	<ul class="settlements">
        {% csrf_token %}
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ totalprice }}</em><br>共计<b>{{ totalcount }}</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>
	</ul>
     </form>

	

{% endblock body %}
{% block bottomfiles %}
    <script src="{{ url }}/js/jquery-1.12.4.min.js"></script>
    <script>
           $('.settlements').find(':checkbox').change(function () {
               is_checked = $(this).prop('checked')
               $('.cart_list_td').find(':checkbox').prop('checked',is_checked)
               update_page_info()
           })

           function update_page_info() {
               totalprice = 0
               totalcount = 0
               $('.cart_list_td').find(':checked').parents('.cart_list_td').each(function () {
                   count = $(this).find('.num_show').val()
                   amount = $(this).find('.col07').text()
                   totalprice += parseFloat(amount)
                   totalcount += parseInt(count)


               })
               $('.settlements').find('em').text(totalprice.toFixed(2))
               $('.settlements').find('b').text(totalcount)
           }
           function update_goods_amount(goods) {
                 count = goods.find('.num_show').val()
                 price = goods.children('.col05').text()
                 amount = parseInt(count)*parseFloat(price)
                 goods.children('.col07').text(amount.toFixed(2)+'元')
           }
           $('.cart_list_td').find(':checkbox').change(function () {
               all_len = $('.cart_list_td').length
               checked_len = $('.cart_list_td').find(':checked').length
               if (checked_len < all_len)  {
                   $('.settlements').find(':checkbox').prop('checked',false)
               }
               else {
                   $('.settlements').find(':checkbox').prop('checked',true)
               }
               update_page_info()
           })
            err_update = false
               total = 0
           function update_remote_cart_info(sku_id,count) {
               csrf = $('input[name="csrfmiddlewaretoken"]').val()
               content = {'count': count, 'sku_id': sku_id, 'csrfmiddlewaretoken':csrf}
               $.ajaxSettings.async = false
               $.post('/cart/update', content, function (data) {
                   if (data.res == 5) {
                       err_update = false
                       total = data.total_count
                   }
                   else {
                       alert(data.errmsg)
                       err_update = true
                   }


               })
               $.ajaxSettings.async = true
           }
           $('.add').click(function () {
               count = $(this).next().val()
               count = parseInt(count) + 1
               sku_id = $(this).next().attr('sku_id')
               {#csrf = $('input[name="csrfmiddlewaretoken"]').val()#}
               {#content = {'count': count, 'sku_id': sku_id, 'csrfmiddlewaretoken':csrf}#}

              update_remote_cart_info(sku_id,count)

               if (err_update ==  false){
                   $(this).next().val(count)

                   update_goods_amount($(this).parents('ul'))

                   is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
                   if (is_checked) {

                       update_page_info()
                   }
                   $('.total_count').children('em').text(total)
               }
           })
            $('.minus').click(function () {
                count = $(this).prev().val()
               count = parseInt(count) - 1
                if(count <= 0) {
                    return
                }
               sku_id = $(this).prev().attr('sku_id')

               update_remote_cart_info(sku_id,count)



               if (err_update ==  false){
                   $(this).prev().val(count)

                   update_goods_amount($(this).parents('ul'))

                   is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
                   if (is_checked) {

                       update_page_info()
                   }
                   $('.total_count').children('em').text(total)
               }
            })
           val  = 0
            $('.num_show').focus(function () {
                val = $(this).val()
            })
            $('.num_show').blur(function () {
                count = $(this).val()
                if (isNaN(count) || count.trim().length == 0 || parseInt(count)<=0) {
                    $(this).val(val)
                    return
                }
                sku_id = $(this).attr('sku_id')
                update_remote_cart_info(sku_id,count)
                if (err_update ==  false){
                   $(this).prev().val(count)

                   update_goods_amount($(this).parents('ul'))

                   is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
                   if (is_checked) {

                       update_page_info()
                   }
                   $('.total_count').children('em').text(total)
               }
               else {
                     $(this).val(val)
                }
            })
            $('.cart_list_td').children('.col08').children('a').click(function () {
                sku_ul = $(this).parents('ul')
                csrf = $('input[name="csrfmiddlewaretoken"]').val()
                sku_id = $(this).parents('ul').find('.num_show').attr('sku_id')
                content = {'csrfmiddlewaretoken':csrf,'sku_id':sku_id}
                $.post('/cart/delete',content,function (data) {
                    if (data.res == 3) {
                        total_count = data.total_count
                        sku_ul.remove()
                        is_checked = sku_ul.find(':checkbox').prop('checked')
                        if (is_checked) {
                            update_page_info()
                        }
                        $('.total_count').children('em').text(total_count)
                    }
                    else {
                        alert(data.errmsg)
                    }
                })

            })


    </script>
{% endblock bottomfiles  %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block topfile %}
	<script type="text/javascript" src="{{ url }}/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="{{ url }}/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="{{ url }}/js/slide.js"></script>
{% endblock topfile %}


	{% block body %}

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			<li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>

            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goodsbanners %}
				<li><a href="{% url 'goods:detail' banner.sku.id %} "><img src="{{ url }}/media/{{ banner.image }}" alt="幻灯片"></a></li>

               {% endfor %}
            </ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for promotion in promotions %}
			<a href="{{ promotion.url }}"><img src="{{ url }}/media/{{ promotion.image }}"></a>

            {% endfor %}
		</div>
	</div>
   {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">

			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for text in type.text_banners %}
				    <a href="{% url 'goods:detail' text.sku.id %}">{{ text.sku.name }}</a>

                {% endfor %}
			</div>
			<a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ url }}/media/{{ type.image }}"></div>
			<ul class="goods_list fl">
                {% for image in type.image_banners %}
				<li>

					<h4><a href="{% url 'goods:detail' image.sku.id %}">{{ image.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' image.sku.id %}"><img src="{{ url }}/media/{{ image.sku.image }}"></a>
					<div class="prize">¥ {{ image.sku.price }}</div>
				</li>
                {% endfor %}
            </ul>
       </div>
    </div>
   {% endfor %}
 {% endblock body %}

	{% block bottomfiles %}
	<script type="text/javascript" src="{{ url }}/js/slide.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
    {% endblock bottomfiles %}

templates/list.html
{% extends 'base_detail_list.html' %}

	{% block title %}天天生鲜-商品列表{% endblock title %}

{% block main_content %}






	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' type.id 1 %}?sort='default'">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for new_sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' new_sku.id %}?sort=default"><img src="{{ url }}/media/{{ new_sku.image }}"></a>
						<h4><a href="#">{{ new_sku.name }}</a></h4>
						<div class="prize">￥{{ new_sku.price }}</div>
					</li>

                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id page_skus.number %}?sort=default" {% if sort == 'default' %} class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id page_skus.number %}?sort=price" {% if sort == 'price' %} class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id page_skus.number %}?sort=sales" {% if sort == 'sales' %} class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
			    {% for sku in page_skus %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ url }}/media/{{ sku.image }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if page_skus.has_previous %}
				    <a href="{% url 'goods:list' type.id page_skus.previous_page_number %}?sort={{ sort }}"><上一页</a>
                {% endif %}
                {% for pindex in pages %}
				<a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" {% if pindex == page_skus.number %} class="active"{% endif %}>{{ pindex }}</a>
			    {% endfor %}
                {% if page_skus.has_next %}
				    <a href="{% url 'goods:list' type.id page_skus.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>



{% endblock main_content %}

templates/login.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block title %}天天生鲜登录{% endblock title %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="{% static 'images/logo02.png'%}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{ username }}">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" checked="{{ check }}">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
                    {{ errmsg }}
				</div>
			</div>
		</div>
	</div>
    	{{ errmsg }}
{% endblock body %}